### ISSUE TITLE
Web apps share icons with browser

### ISSUE THREAD

**Issue by Mek101** [linuxmint/webapp-manager#103] opened 2021-04-20 21:27 UTC
![Schermata da 2021-04-20 23-17-45](https://user-images.githubusercontent.com/34246799/115465828-7846ca80-a22f-11eb-8b12-d14a6c555669.png)

As exemplified here, the main Firefox windows and the Youtube webapp share the same "handler", which in practice means that the web app is treated as a normal Firefox window instead of a separated application.

OS Manjaro
GNOME 3.38
Firefox 88 (Flatpak)

Could be related to #100

**Comment by tobiasrenkin** [comment] 2021-04-21 13:46
The same thing happens for me with chrome-based apps but not firefox-based apps.

Linux Mint
XFCE 4.14
Chrome 90.0.4430.72 // Firefox 87

**Comment by hsbasu** [comment] 2021-05-01 14:03
I also have the same issue on chrome based browsers only. The windows are clubbed under the icon associated to the first opened instance.
Ubuntu Mate 20.04.2
Chrome 90

**Comment by Coeur-Noir** [comment] 2021-06-04 16:54
As a workaround, you may avoid this « shared icon » using isolated profile for each web-app.

**Comment by nicolashainaux** [comment] 2021-10-12 07:59
> ... isolated profile for each web-app.

@Coeur-Noir How do you do that?

**Comment by Mek101** [comment] 2021-10-13 11:39
> As a workaround, you may avoid this « shared icon » using isolated profile for each web-app.

This only works on chromium browsers, since Firefox profiles are always isoleted

**Comment by nicolashainaux** [comment] 2021-10-13 12:37
> > As a workaround, you may avoid this « shared icon » using isolated profile for each web-app.
> 
> This only works on chromium browsers, since Firefox profiles are always isoleted

OK, that's why I didn't see the option.

**Comment by Mek101** [comment] 2021-10-15 07:18
> FYI, separate icon for firefox-based webapps is already fixed with PR #49

Doesn't work on gnome. It highlights as active the youtube app for a second, then as soon as the window appears it switches to the firefox icon

**Comment by Mek101** [comment] 2021-10-15 07:25
According to looking glass, the youtube app has the wm class `firefox` and the `org.mozilla.firefox` app, like the browser

**Comment by winiciuscota** [comment] 2021-11-09 17:45
Is there any other workaround for chrome-based that doesn't involve using isolated profiles? one might have multiple google apps(gmail, spreadsheets, maps) and doesn't want to have multiple login instances fore each one of them, which could also be considered a suspicious behavior by google

**Comment by bdombro** [comment] 2022-01-07 14:18
I'm on Majaro and have this problem with both Firefox and ungoogled-chrome (flatpak). I got it working by installing ungoogled-chrome from AUR (aka community repo aka NOT flatpak) and checking "isolated profile"

**Comment by Khraut** [comment] 2022-02-05 19:09
I found a workaround for this problem. It has really annoyed me on me on Manjaro-Gnome (switched from Plasma to Gnome, in Plasma this issue did not exist). 

I played around with the .deskop files in `/home/.local/share/applications/` and found a really easy fix for this (at least i hope so, i don't know if there are any problems with this way of fixing, at first glance, there is only one drawback).

So here is the fix which worked for me:

1. create your WebApp with the WebApp-Manager
2. go to `home\.local\share\applications` and find the matching `.desktop` file
3. open this file with an editor
4. append this at the end of the line which starts with "Exec" `--name=yourWebApp`
so that it looks something like this:
 `Exec=sh -c 'XAPP_FORCE_GTKWINDOW_ICON=discord firefox .......... --name=discord'`

5. change the parameters of the lines which start with "Icon" and "StartupWMClass" to `yourWebApp`
in this example it would look like this:
`Icon=discord`
`StartupWMClass=discord`

Done!

So as i wrote earlier there is also one downside of this workaround, the WebApp-Manager does not show the changed WebApps anymore. So if you want to delete or edit the changed WebApps you have to do this with the .desktop files, but i think this is still a good deal. 

I hope this helps and i also hope this is the only downside of this, since I am far from being an expert, I can not estimate this exactly.

**Comment by bdombro** [comment] 2022-02-05 22:01
Update: My method didn't work because the icon would be shared in the dock if you had multiple apps open.

I also tried @Khraut 's method which almost worked, except it had an issue with following links outside of the initial domain. For example, if creating an app for Fastmail, Reddit, FB Messenger, when someone sends a link in a message and I click it, I would expect the link to be opened in a new browser window. Instead, the webapp opens the link and now it's stuck.

I found a solution which works well for me: 
1. nativefier - a nodejs app that packages any website into an electron app
2. A script I wrote which installs the electron app into gnome

Src: https://github.com/bdombro/nativefier-linux

**Comment by Khraut** [comment] 2022-02-06 09:27
@bdombro 
I also encountered the issue that there is no new browser windows that opens up when you are clicking on a link inside the webapp. I fixed this with going to the Firefox settings inside the webapp and unchecking the "Open links in tabs instead of new windows" option. Now the link will open up a new window, sadly this window is not like your regular browser window (it shows without address-bar) but for me this is not that big of a problem. 

I also found this python script on GitHub: https://github.com/marten-de-vries/mozapp

It seems to also be able to generate webapps that does not share their icon with the browser. But i don't know how these behave on this issue.

**Comment by Coeur-Noir** [comment] 2022-07-18 18:10
@bkmo same as here https://github.com/filips123/PWAsForFirefox/issues/80#issuecomment-1160839905 maybe ?

**Comment by bkmo** [comment] 2022-07-18 18:16
All I am suggesting is adding is a new parameter  "--name (same as classname)"  to the exec line of the .desktop file. Easy fix for me, and could be added at app creation time from the webapp-manager.

**Comment by Coeur-Noir** [comment] 2022-07-19 20:45
Ok, ok, I was not saying you're wrong in any way ;-)

I just wonder why I don't need to add _--name_ in my situation.

My « Exec= » lines look like : 
```
Exec=firefox --new-window -P Deezer https://www.deezer.com/fr/ --class Deezer %u
```
I guess _-P_ « calling » the name of a profile is quite the same as _--name_ ? ? ?

In launchers, mind the _Exec_ and _StartupWMClass_ entries : 
- --new-window
- -P
- --class
- %u ( not sure if it's mandatory )

In _profiles.ini_, mind the _naming_ of each Firefox profile, the same wording for each matters.
The _name_ of a profile must match the part after the dot in _path_
```
[Profile2]
Name=Deezer
IsRelative=1
Path=dj4ng0.Deezer
```

**Comment by bkmo** [comment] 2022-07-19 21:02
Are you saying webapp-manager currently works properly by placing each app seperately in the tray? Mine does not. It also does not. It also does not use current default profiles in Firefox, therefore no profiles.ini. My solution works by simply adding the --name parameter to the Exec= of the .desktop file. Try it!  Are you actually using webapp-manager or your own custom profile solution?

**Comment by Coeur-Noir** [comment] 2022-07-25 13:57
_It also does not use current default profiles in Firefox, therefore no profiles.ini_
You certainly have a _profiles.ini_ in _.mozilla/firefox_ but indeed browser's profiles used by web-app-manager are ( were ? ) stored into `~/.local/share/ice/firefox`
Therefore the Exec path should probably mention the full path to the needed profile, something like
```
--profile /path/to/.local/share/ice/firefox/one_of_your_webapp
```
hence then
```
Exec=firefox --new-window --profile /path/to/.local/share/ice/firefox/YourWebApp https://www.website.com/ --class YourWebApp %u
```
might be enough ( I still have to understand what --new-window, --no-remote or --new-instance are supposed to change here - but in my situation --new-window is enough to have different icons for different websites, surprisingly. )

The icon is tied to a ( browser's ) profile.

I did use ice web app ( from peppermint OS ) then web-app-manager for years, but no longer today as I can't make it work on my Ubuntu 22.04 - don't know why though.

**Comment by hsbasu** [comment] 2022-07-26 05:03
> I did use ice web app ( from peppermint OS ) then web-app-manager for years, but no longer today as I can't make it work on my Ubuntu 22.04 - don't know why though.

Ubuntu 22.04 uses snap version of firefox. That's why it is not working. Here I am providing the quick fix.
Step 1. If you have created a web-app based on firefox for **gitlab.com**, it's profile would be located in `~/.local/share/ice/firefox`. Copy this to `~/snap/firefox/common/.mozilla/firefox`.
Step 2. Modify the .desktop file. In the **Exec** line you would have something like
```
Exec=sh -c 'XAPP_FORCE_GTKWINDOW_ICON=~/.local/share/ice/icons/GitLab.png firefox --class WebApp-GitLab3098 --profile ~/.local/share/ice/firefox/GitLab3098 --no-remote http://www.gitlab.com'
```
Change the path after `--profile` to 
```
Exec=sh -c 'XAPP_FORCE_GTKWINDOW_ICON=~/.local/share/ice/icons/GitLab.png firefox --class WebApp-GitLab3098 --profile ~/snap/firefox/common/.mozilla/firefox/GitLab3098 --no-remote http://www.gitlab.com'
```
Note: I have have changed my home directory with `~`, but in the .desktop files it should be replaced with `/home/<username>`

**Comment by Coeur-Noir** [comment] 2022-07-26 11:40
@hsbasu thanks for caring but I'm not the one asking for help ;-) And you're right about the _--profile_ path in case of a snap, it should be located somewhere inside `/home/<user>/snap/firefox/…`

I don't use Firefox as a snap in my Ubuntu 22.04, it's a manual installation from https://www.mozilla.org/en-US/firefox/all/#product-desktop-release, so here it's the expected and legacy paths inside $HOME.

Regarding WebApp Manager in Ubuntu 22.04, as stated here https://www.omgubuntu.co.uk/2022/07/install-linux-mint-apps-on-ubuntu-ppa « the Webapp Manager tool (…) did NOT work with the Firefox Snap on my system. »

And I can confirm it also does not work as expected with my « manual installation » : the WebApp opens without title-bar, even if I set Firefox to use a title-bar, making it very uncomfortable to manage its window. ( Here I suspect something related to Wayland or gtk4 and the script that modifies the Firefox interface. )

**Comment by hsbasu** [comment] 2022-07-26 18:19
I am really sorry. I forgot that ubuntu by default uses Gnome desktop. Thanks for reminding. And I am using Cinnamon. I also have Gnome. I'll check what happens there.

**Comment by renatofrota** [comment] 2023-09-01 21:24
Firefox webapps uses proper icon as set for them. The generated .desktop has:

```
Exec=sh -c 'XAPP_FORCE_GTKWINDOW_ICON=web-whatsapp firefox --class WebApp-WhatsApp6785 --profile /home/avell/.local/share/ice/firefox/WhatsApp6785 --no-remote https://web.whatsapp.com'
```

Google Chrome webapps are showing Google Chrome's icon. The generated .desktop uses no XAPP_FORCE_GTKWINDOW_ICON.

Editing Google Chrome's one to be like the Firefox's (with XAPP_FORCE_GTKWINDOW_ICON), kinda works but... all windows of Google Chrome will use the same icon as the 1st launched app.

- Launch WhatsApp web -> WhatsApp icon
- Launch Google Chrome -> WhatsApp icon

Although I can't explain why it works for Firefox, I suspect it may have some relation to this this commit: https://github.com/linuxmint/xapp/commit/ccc70e5625ecab260d01be847fbfc82c4212f933

Any thoughts?

**Comment by digitalextremist** [comment] 2023-09-15 23:43
Joining this existing issue for the problem I have been seeing too: "Shared icon in window lists"

I have several `Mint 21.x` instances with this issue. Are we to the point of having an official approach here, or is this not going to be addressed with a change to the GUI? Seems like all options are workarounds, and all involve manual steps which might regress if you then use the GUI again later? 

Regardless of the annoyance of this issue, it is cool to see how properly organized you all are, and how long-suffering. This ticket being started in 2021 Q2 makes it seem like a good candidate for closure :) Let's get this one off the to-do list!

**Comment by digitalextremist** [comment] 2023-09-22 01:19
Since my last post, I tried @bdombro suggestion: https://github.com/linuxmint/webapp-manager/issues/103#issuecomment-1030706420

I already had `npm` installed, so I just ran the install recommended, and tried it out. Definitely solves the problem, but goes further and allows addition of systray icon for web app, single-instance protection, always on top, etc... if desired, by build flag.

Also it remembers the location of the window between sessions. Web App manager usually started all windows in the left half of the entire screen on the primary display every time, and never remembered otherwise.

Is each native executable >200MB? Well, yes... the browser is packaged with each Electron instance, per overkill usual. But at least now it works while/if Web App manager evolves. Will check back in a year or so :)

**Comment by digitalextremist** [comment] 2023-09-27 18:56
Oh man. So, using `nativefier` is great, except for huge issue: No ad-blocker support whatsoever, with no hope of that in sight. In the case of internal systems that might be fine, but even if you are using it just for webmail for example, that is going to be riddled with ads very often. And the support for ad-blocking seems to be either dead, or up 💩 creek without a paddle.

https://github.com/nativefier/nativefier/issues/1532

**Comment by jberlyn** [comment] 2023-10-28 06:21
I am experiencing something similar on Arch Linux with KDE Plasma 5.27.9 and Wayland. When the app first opens, the correct icon is shown in the taskbar, but then is collapsed into the Firefox icon. The app is also showing as Firefox in the overview window or task switcher (ALT+TAB). This does not happen under X11.

**Comment by nuovodna** [comment] 2023-10-30 22:55
same here, Fedora 39 + Gnome 45. 
Web WhatsApp shows Firefox icon in task switcher (not in launcher), Chromium version works well

**Comment by saschaeggi** [comment] 2023-10-31 23:14
Same here Fedora 38 + Gnome 44

**Comment by saschaeggi** [comment] 2023-11-09 12:26
I can confirm that just adding `--name WebApp-[NAMEHERE]` actually solves the problem under Wayland.

Tested on Fedora 38 + Gnome 44 / Fedora 39 + Gnome 45

**Comment by saschaeggi** [comment] 2023-11-09 12:36
I've created a MR with a fix: https://github.com/linuxmint/webapp-manager/pull/272

**Closed** 2023-11-28 11:57 UTC

**Comment by saschaeggi** [comment] 2023-11-29 07:37
@digitalextremist the related MR fixes the window handling in wayland

**Comment by tobiasrenkin** [comment] 2023-11-29 08:39
@saschaeggi perhaps it is a bit early to close the bug then, given that it was originally reported for x.org ?

**Comment by saschaeggi** [comment] 2023-11-29 08:53
@tobiasrenkin I leave this decision to the maintainer. Have you tested if this also fixes your issue in X11?

**Comment by Th3Rom3** [comment] 2023-12-28 19:12
I can second this observation for KDE Plasma 5.27.9 on Wayland. Task-Manager icon displays correctly now. Window title and Overview show the default Wayland icon.

**Comment by RYJASM** [comment] 2025-06-02 16:13
Just want to say this bug is still present in Linux Mint 22 Cinnamon. And it's still as annoying as ever.

**Comment by ivaaane** [comment] 2025-08-20 17:43
Still having this issue in Linux Mint 22.1 Cinnamon as well, using Librewolf

**Comment by winiciuscota** [comment] 2025-10-15 05:25
still still present on plasma 6 with xorg
