### ISSUE TITLE
Is it possible to use uBlock Origin?

### ISSUE THREAD

**Issue by Raytle** [linuxmint/webapp-manager#211] opened 2022-09-30 01:16 UTC
I read #183 but I don't see how to use it.

**Comment by begin-theadventure** [comment] 2022-10-10 11:44
Firefox: Ctrl+Shift+A
Chrome: F1

**Comment by Raytle** [comment] 2022-10-10 18:42
I want to know if it is possible to use uBlock Origin with Webapp Manager. I don't see how to do it.

**Comment by begin-theadventure** [comment] 2022-10-10 19:07
Pull request 183 has been closed and not merged, which means that this feature is not available.
Just install uBlock Origin from the store or use a browser that has it pre-installed, such as LibreWolf or Brave, which has its own blocker.

**Comment by Raytle** [comment] 2022-10-10 21:24
I have Brave, Chromium, and Google Chrome installed. None of them enable me to granularly customize font sizes like Firefox does.

If I use any of the three Chromium-based browsers above I don't need to bother using Webapp Manager because I can simply create web apps with `More tools –> Create shortcut...`

The problem I face, of course, is that Firefox doesn't have built-in support for web apps.

**Comment by Raytle** [comment] 2022-10-10 21:26
I have installed uBlock origin in Firefox. uBlock origin works properly when I run Firefox in the conventional manner; however, uBlock origin fails to work when I open a web app with Webapp Manager.

**Comment by securearth** [comment] 2022-11-10 18:13
> 

Because each web app created runs in its own profile, so you need to install the extension in its own profile

**Comment by alvilag** [comment] 2022-12-17 09:23
Hello,

When I click the 'add to firefox' button on the ublock extension page, it does nothing. I am on linux mint 21, using the standard .deb firefox for linux mint, and everything is up to date. Note that on my standard firefox profile (not the webapp manager's), ublock origin is installed and works.

What should I do?

**Comment by morenathan** [comment] 2023-01-03 21:41
I get this same issue too. No extension, but more specifically uBlock Origin which is what I'm after, will install from the Firefox Add-ons page.

Click the "Add to Firefox" button will cause it to act like it's going to install, then it just goes back to "Add to Firefox". Restarting the Web app doesn't help. Restarting all of Firefox doesn't help.

**Comment by morenathan** [comment] 2023-01-03 22:05
I have also noticed that when the permissions popup in Firefox is shown that it blips in and out of existence. I'm unable to actually click to continue installation. This the same for allowing notifications. 

Maybe this is why?

In looking at the command line for the launcher in htop, there doesn't appear to be anything out of the ordinary that would prevent it from running normally. I have a script that builds this kind of Firefox "app" before using your program and that works.

**Comment by morenathan** [comment] 2023-01-03 22:09
Okay, so the issue is with the userChrome.css injection. I'll look at it later unless someone comes up with the solution sooner. One of the used classes is problematic and causing extensions and other permission dialogs to no properly show and this is the root of the issue.

A temporary fix would be to enable the navbar, install your extensions, then edit the web app to disable the nav bar which will work for now.

**Comment by morenathan** [comment] 2023-01-03 22:21
Temporary fix for using extensions while having the Navigation Bar hidden;

1. Create a profile with the Navigation Bar hidden and just leave it.
2. Create a profile you want to use with the Navigation Bar present.
3. Install all the extensions you want installed.
4. Also, answer any security/permission popups for other questions like notifications you may want.
5. Copy the chrome/userChrome.css from the profile created in step 1 to chrome/userChrome.css to the profile created in steap 2. Profiles are stored in ~/.local/share/ice/firefox/... or $XDG_DATA_HOME/ice/firefox (I'm not sure but hope it's the latter).

That works for me, for now. It's a PITA but it will allow you to install any extension and then have a hidden bar. Keep in mind if you *EDIT* the web app profile in the interface and tick the navigation bar option you will lose your installed extensions.

**Comment by alvilag** [comment] 2023-02-05 15:41
> A temporary fix would be to enable the navbar, install your extensions, then edit the web app to disable the nav bar which will work for now.

This solution worked for me! Many thanks.

**Closed** 2023-07-22 16:03 UTC
